#include<Stdio.h>
#include<stdlib.h>
#include<time.h>

void rps(char x,char y){
    if (x == y){
        printf("IT'S A TIE,AS YOU HAVE TAKEN OUT %c AND SYSTEM HAS TAKEN OUT %c",x,y);
    } else if(x == 'r' && y == 'p'){
        printf("SYSTEM WINS,AS YOU HAVE TAKEN OUT %c AND SYSTEM HAS TAKEN OUT %c",x,y);
    } else if(x == 'r' && y == 's'){
        printf("PLAYER WINS,AS YOU HAVE TAKEN OUT %c AND SYSTEM HAS TAKEN OUT %c",x,y);
    } else if(x == 'p' && y == 'r'){
        printf("PLAYER WINS,AS YOU HAVE TAKEN OUT %c AND SYSTEM HAS TAKEN OUT %c",x,y);
    } else if(x == 'p' && y == 's'){
        printf("SYSTEM WINS,AS YOU HAVE TAKEN OUT %c AND SYSTEM HAS TAKEN OUT %c",x,y);
    } else if(x == 's' && y == 'r'){
        printf("SYSTEM WINS,AS YOU HAVE TAKEN OUT %c AND SYSTEM HAS TAKEN OUT %c",x,y);
    } else if(x == 's' && y == 'p'){
        printf("PLAYER WINS,AS YOU HAVE TAKEN OUT %c AND SYSTEM HAS TAKEN OUT %c",x,y);
    }
}
int main(){
    char ch;// character entered by the player
    printf("enter the character from r, s, p : ");
    scanf("%c",&ch);
    // remember only 3 characters can be entered by the user i.e. r = rock,p = paper,scissor = s;
    char comp;//character generated by the system;
    int number;
    srand(time(0));
    number = rand()%100 + 1;//generating a random number between 1 to 100;
    if (number >= 1 && number <= 33){
        comp = 's';
    } else if(number >= 34 && number <= 66){
        comp = 'p';
    } else if(number >= 67 && number <= 100){
        comp = 'r';
    }
    rps(ch,comp);
    return 0;
}
